// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  silderbar: [
    { type: 'autogenerated', dirName: 'main' },
    {
      type: 'category',
      label: 'Protocol',
      items: [ { type: 'autogenerated', dirName: 'protocol' } ]
    },
    {
      type: 'category',
      label: 'Roadmap',
      items: [ { type: 'autogenerated', dirName: 'roadmap' } ]
    },
    // {
    //   type: 'category',
    //   label: 'Advanced',
    //   items: [ { type: 'autogenerated', dirName: 'advanced' } ]
    // }
  ],
};

module.exports = sidebars;
